config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :sessions, only: [:new, :destroy, :create]

  root 'welcome#hello'

  # index
  get '/posts' => 'posts#index', as: :posts

  # new
  get '/posts/new' => 'posts#new', as: :new_post
  post 'posts' => 'posts#create'

  # show
  get '/posts/:id' => 'posts#show', as: :post

  # edit
  get '/posts/:id/edit' => 'posts#edit', as: :edit_post

  # update
  patch 'posts/:id' => 'posts#update'

  # delete
  delete '/posts/:id' => 'posts#destroy'

  get '/sessions/new' => 'sessions#new'
  get '/users/new' => 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def authenticate_user!
        redirect_to new_sessions_path, notice: "Please sign in" unless user_signed_in?
    end
    
    def user_signed_in?
        current_user.present?
    end
    helper_method :user_signed_in?
    
    def current_user
        @current_user ||= User.find_by_id session[:user_id]
    end
    helper_method :current_user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: [:show]

    def index
        @posts = Post.all.order(created_at: :desc)
    end

    def new
        @new_post = Post.new
    end

    def create
        @new_post = Post.new params.require(:post).permit(:title, :body)
        if @new_post.save
            flash[:notice]
            redirect_to posts_path
        else
            render new_post_path
        end
    end

    def show
        @post = Post.find(params[:id])
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        if @post.update params.require(:post).permit(:title, :body)
            redirect_to post_path(@post)
        else
            render edit_post_path
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end
  
    def create
      @user = User.find_by_email params[:email]
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to posts_path, notice: "Logged in"
      else
        flash[:alert] = "Wrong email or password"
        render :new
      end
    end
  
    def destroy
      session[:user_id] = nil
      redirect_to root_path, notice: "Logged out!"
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
      @user = User.new
    end
  
    def create
      @user = User.new user_params
      if @user.save
        session[:user_id] = @user.id
        redirect_to posts_path, notice: "Logged In!"
      else
        render :new
      end
    end
  
    private
  
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
  end
  

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def hello
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRailsAuthentication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>

    <div class="login-div">
      <% if user_signed_in? %>
        Hello <%= current_user.name %>,
          <%= link_to "Logout" , sessions_path, method: :delete, data: {confirm: "are you sure you want to log out?" }%>
            <% else %>
              <%= link_to "Login" , new_sessions_path %> |
                <%= link_to "Sign Up" , new_user_path %>
                  <% end %>
    </div>

    <div class="nav-links">
      <%= link_to "Blog Index" , posts_path %> |
        <%= link_to "New Post" , new_post_path %>
    </div>
    <hr>

    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>This is the edit page</h1>
<hr>

<div class="edit-div">
<%= form_for(@post) do |f| %>
<%= f.label :title %> <br>
<%= f.text_field :title, :placeholder => "Title" %> <br> <br>
<%= f.label :body %> <br>
<%= f.text_area :body, :placeholder => "Your blog" %> <br> <br>
<%= f.submit "Edit Post", :class => "btn btn-primary" %>
<% end %>
</div>

app/views/posts/index.html.erb
<h1 class="index-page">Welcome to your Blogs Index page</h1>
<hr>

<%= @posts.each do |post| %>
<h2><%= link_to post.title, post_path(post) %></h2>
<% end %>

app/views/posts/new.html.erb
<h1>This is the New form page</h1>
<hr>

<div class="new-div">
<%= form_for(@new_post) do |f| %>
<%= f.label :title %> <br>
<%= f.text_field :title, :placeholder => "Title" %> <br> <br>
<%= f.label :body %> <br>
<%= f.text_area :body, :placeholder => "Your blog" %> <br> <br>
<%= f.submit "Create Post", :class => "btn btn-primary" %>
<% end %>
</div>

app/views/posts/show.html.erb
<h1>This is the Show page</h1>
<hr>
<div class="show-div">
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<p><%= @post.created_at %></p>
<%= link_to "Edit", edit_post_path(@post) %>
<%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" } %>
</div>

app/views/users/new.html.erb
<div class="signup-div">
<h1>Sign Up</h1>
<hr>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :name %> <br>
    <%= f.text_field :name, :placeholder => "Full Name" %> <br> <br>
  </div>
  <div>
    <%= f.label :email %> <br>
    <%= f.email_field :email, :placeholder => "Email" %> <br> <br>
  </div>
  <div>
    <%= f.label :password %> <br>
    <%= f.password_field :password, :placeholder => "Password" %> <br> <br>
  </div>
  <div>
    <%= f.label :password_confirmation %> <br>
    <%= f.password_field :password_confirmation, :placeholder => "Password Confirmation" %> <br> <br>
  </div>
  <%= f.submit %>
<% end %>
</div>

app/views/welcome/hello.html.erb
<h1 style="text-align: center;">Hello and Welcome! Please sign up or login to view and post</h1>